# Description:
# This file contains cURL requests for testing API endpoints using the REST Client extension.
# Base URL: http://127.0.0.1:8000

@baseUrl = http://127.0.0.1:8000

### Server Health Check
# Checks if the server is running and accessible.
curl -X GET {{baseUrl}}/

### Signup Teacher
# Registers a new teacher account.
curl -X POST {{baseUrl}}/api/v1/auth/?type=signup_teacher \
     -H "Content-Type: application/json" \
     -d '{
       "name": "Ayesha",
       "email": "ayesha@example.com",
       "password": "securepassword123",
       "phone_number": "+1234567890",
       "teaching_class": "CLASS_1"
     }'

### Signup Student
# Registers a new student account.
curl -X POST {{baseUrl}}/api/v1/auth/?type=signup_student \
     -H "Content-Type: application/json" \
     -d '{
       "full_name": "zoya",
       "email": "zoya@example.com",
       "password": "studentpassword123",
       "student_class": "CLASS_1",
       "parents_email": "parent@example.com",
       "parents_phone_number": "+0987654321"
     }'

### Teacher Login
# Authenticates a teacher using email.
curl -X POST {{baseUrl}}/api/v1/auth/?type=teacher_login \
     -H "Content-Type: application/json" \
     -d '{
       "email": "ayesha@example.com",
       "password": "securepassword123"
     }'

### Student Login
# Authenticates a student using eamil .
curl -X POST {{baseUrl}}/api/v1/auth/?type=student_login \
     -H "Content-Type: application/json" \
     -d '{
       "email": "zoya@example.com",
       "password": "studentpassword123"
     }'

